### ISSUE TITLE
Error when cannot find the image

### ISSUE THREAD

**Issue by xycyx** [xycyx/AutoSlides#3]
If the `filter_images_by_features()` cannot find the image, it will exit the program
```
Traceback (most recent call last):
  File "AutoSlides.py", line 61, in <module>
    main(sys.argv[1:])
  File "AutoSlides.py", line 53, in main
    prs = create_slides(df, prs)
  File "/Users/yxcheng/GitRepos/AutoSlides/utils.py", line 625, in create_slides
    prs = build_the_slide(prs, df, 'CC', scan_time)
  File "/Users/yxcheng/GitRepos/AutoSlides/utils.py", line 604, in build_the_slide
    img_paths.append(path[0])
IndexError: list index out of range
```

**Comment by xycyx** [comment]
fixed by 57d8a0ed3a2dbd2b54529060e0a45325922ac9cf
